name: PR

on:
  pull_request_target:
    types: [opened, synchronize]
  pull_request:
    branches:
    - 'main'
    
jobs:
  runPR:
    runs-on: ubuntu-latest
#     container:
#       image: cicd-oci-release-orl.repo.orl.eng.hitachivantara.com/lumada-common-services/data-plane:20230207.5-maven-node
    environment: frogbot
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install --file pom.xml

    - name: FrogBot
      uses: jfrog/frogbot@v2.8.1
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         JF_WORKING_DIR: ./L1Module2
#         JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
